general_setting:
  num_initial_points: 11
  initial_points_selection_method: 'sobol'
  initial_points: []
  num_iterations: 60
  repetitions: 30
  random_seed: False
  seeds: [0,1,2,3,4,5,6,7,8,9]
  output_path: "./outputs/outputs_ligen"
  delete_previous_output: False
  debug: False
  verbose: 0
  max: -567.312555400384
optimizer:
  f: None
  pbounds: ['ALIGN_SPLIT', 'OPTIMIZE_SPLIT', 'OPTIMIZE_REPS', 'CUDA_THREADS', 'N_RESTART', 'CLIPPING', 'SIM_THRESH', 'BUFFER_SIZE']
  bounds: [[8, 72.01], [8, 72.01], [1, 5.01], [32, 256.01], [256, 1024.01], [10, 256.01], [1, 4.01], [1, 50.01]]
  dataset: "resources/ligen_synth_table.csv"
  target_column: '-RMSD^3*TIME'
stopping_criteria:
  stopping_criteria: False
  hard_stop: False
  conjunction: "or"
acquisition_info:
  acquisition_function: "ei"
  ml_on_bounds: True
  ml_on_target: True
  consider_max_only_on_feasible: True
  epsilon_greedy: True
  adaptive_method: True
  memory_queue_len: 71
  relaxation: False
  epsilon_greedy_parameters:
    prob_random_pick: 0.1
  adaptive_method_parameters:
    ucb_af:
      initial_beta: 1.0
      beta_h: 10.0
    kernel: RBF
    RBF_parameters:
      sigma_2: 1.0
      initial_l: 1.0
      l_h: 10.0
    Matern_parameters:
      initial_nu: 2.5
      nu_h: 10.0
  eic:
    eic_ml_var: "C"
    eic_bounds: [0, 17000]
    eic_P_function: 
      parameters:
        - x
      body: |
        return x[:,3]
    eic_Q_function: None
    eic_ml_exp_B: None
  ml_on_bounds_parameters:
    ml_target: 'RMSD_0.75'
    ml_bounds: [0.0, 2.1]
    ml_bounds_coeff: [0.9, None]
    ml_bounds_type: indicator
    ml_bounds_model: Ridge
    Ridge:
      alpha: 0.099
    XGBoost:
      gamma: 0.312
      learning_rate: 0.407
      max_depth: 10
      n_estimators: 10
  ml_on_target_parameters:
    ml_target_type: None
    ml_target_model: Ridge
    Ridge:
      alpha: 0.959
    XGBoost:
      gamma: 7.789
      learning_rate: 0.467
      max_depth: 10
      n_estimators: 10
    indicator_parameters:
      coeff: [1.111, None]
    sum_parameters:
      ml_target_gamma_iter0: 0
      ml_target_gamma_iterN: 30
      ml_target_gamma_max: 0.5    