general_setting:
  num_initial_points: 3
  initial_points_selection_method: 'sobol'
  initial_points: []
  num_iterations: 10
  repetitions: 30
  random_seed: False
  seeds: [916634440]
  output_path: "./outputs/test"
  delete_previous_output: False
  debug: False
  verbose: 0
  max: -0.174361111
optimizer:
  f: None
  pbounds: ['parallelism_ffmpeg-0', 'parallelism_librosa', 'parallelism_ffmpeg-1', 'parallelism_ffmpeg-2', 'parallelism_deepspeech']
  bounds: [[2,4.00001], [2,6.00001], [2,4.00001], [2,8.00001], [2,4.00001]]
  dataset: "resources/OSCAR-P_combinatorial.csv"
  target_column: "-cost"
stopping_criteria:
  stopping_criteria: False
  hard_stop: False
  conjunction: "or"
acquisition_info:
  acquisition_function: "ucb"
  ml_on_bounds: True
  ml_on_target: True
  consider_max_only_on_feasible: True
  epsilon_greedy: True
  adaptive_method: False
  memory_queue_len: 13
  relaxation: False
  epsilon_greedy_parameters:
    prob_random_pick: 0.1
  adaptive_method_parameters:
    ucb_af:
      initial_beta: 1.0
      beta_h: 10.0
    kernel: RBF
    RBF_parameters:
      sigma_2: 1.0
      initial_l: 1.0
      l_h: 10.0
    Matern_parameters:
      initial_nu: 2.5
      nu_h: 10.0
  eic:
    eic_ml_var: "C"
    eic_bounds: [0, 17000]
    eic_P_function: 
      parameters:
        - x
      body: |
        return x[:,3]
    eic_Q_function: None
    eic_ml_exp_B: None
  ml_on_bounds_parameters:
    ml_target: "total_time"
    ml_bounds: [0.0, 300.00001]
    ml_bounds_coeff: [0.9, None]
    ml_bounds_type: probability
    ml_bounds_model: Ridge
    Ridge:
      alpha: 0.579
    XGBoost:
      gamma: 9.363
      learning_rate: 0.197
      max_depth: 10
      n_estimators: 10
  ml_on_target_parameters:
    ml_target_type: probability
    ml_target_model: Ridge
    Ridge:
      alpha: 0.011
    XGBoost:
      gamma: 0.128
      learning_rate: 0.269
      max_depth: 10
      n_estimators: 10
    indicator_parameters:
      coeff: [1.111, None]
    sum_parameters:
      ml_target_gamma_iter0: 0
      ml_target_gamma_iterN: 5
      ml_target_gamma_max: 0.5    