general_setting:
  num_initial_points: 3
  initial_points: []
  num_iterations: 60
  repetitions: 30
  random_seed: False
  seeds: [0,1,2,3,4,5,6,7,8,9]
  output_path: "./outputs/stereomatch"
  delete_previous_output: False
  debug: False
  verbose: 0
  max: -40196
optimizer:
  f: None
  pbounds: ["confidence", "hypo_step", "max_arm_length", "num_threads"]
  bounds: [[14, 64.00001], [1, 3.00001], [1, 16.00001], [1, 32.00001]]
  dataset: "resources/stereomatch.csv"
  target_column: "-cost"
stopping_criteria:
  stopping_criteria: False
  hard_stop: False
  conjunction: "or"
acquisition_info:
  acquisition_function: "ei"
  ml_on_bounds: True
  ml_on_target: True
  consider_max_only_on_feasible: True
  epsilon_greedy: True
  adaptive_method: False
  memory_queue_len: 63
  relaxation: False
  epsilon_greedy_parameters:
    prob_random_pick: 0.1
  adaptive_method_parameters:
    ucb_af:
      initial_beta: 1.0
      beta_h: 10.0
    kernel: RBF
    RBF_parameters:
      sigma_2: 1.0
      initial_l: 1.0
      l_h: 10.0
    Matern_parameters:
      initial_nu: 2.5
      nu_h: 10.0
  eic:
    eic_ml_var: "C"
    eic_bounds: [0, 17000]
    eic_P_function: 
      parameters:
        - x
      body: |
        return x[:,3]
    eic_Q_function: None
    eic_ml_exp_B: None
  ml_on_bounds_parameters:
    ml_target: "time"
    ml_bounds: [0, 17000]
    ml_bounds_coeff: [0.9, None]
    ml_bounds_type: indicator
    ml_bounds_model: Ridge
    Ridge:
      alpha: 0.026
    XGBoost:
      gamma: 1.151
      learning_rate: 0.368
      max_depth: 10
      n_estimators: 10
  ml_on_target_parameters:
    ml_target_type: sum
    ml_target_model: Ridge
    Ridge:
      alpha: 0.025
    XGBoost:
      gamma: 6.552
      learning_rate: 0.381
      max_depth: 10
      n_estimators: 10
    indicator_parameters:
      coeff: [1.111, None]
    sum_parameters:
      ml_target_gamma_iter0: 0
      ml_target_gamma_iterN: 30
      ml_target_gamma_max: 0.5    